### ISSUE TITLE
some wrong

### ISSUE THREAD

**Issue by exp224** [ivanvoid/HHSA#1]
running HHSA.py

Traceback (most recent call last):

  File "<ipython-input-14-33857ee2dd89>", line 81, in <module>
    new_imfs += EMD(env, 3)

  File "D:\Python_Learn\Time_Freq_Analysis\HHSA-master\EMD.py", line 29, in EMD
    maxenv, minenv = max_min_env(h)

  File "D:\Python_Learn\Time_Freq_Analysis\HHSA-master\EMD.py", line 54, in max_min_env
    d = np.diff(signal)

  File "<__array_function__ internals>", line 6, in diff

  File "C:\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 1235, in diff
    raise ValueError("diff requires input that is at least one dimensional")

ValueError: diff requires input that is at least one dimensional

**Comment by ivanvoid** [comment]
ok I rewrite everything, try to run it again. Tell me if it works.
